# Generated by Django 5.2.13 on 2026-04-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_plant_category_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
