# Generated by Django 5.2.13 on 2026-04-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='origin',
            field=models.ManyToManyField(to='plant.origin'),
        ),
    ]
