# Generated by Django 5.2.13 on 2026-04-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_plant_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('flag', models.ImageField(default='flags/default.jpg', upload_to='flags/')),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='origin',
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(to='plant.country'),
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
    ]
